// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * webview が受け取るメニューの操作。`app:action` の積荷です。
 *
 * 名前は TypeScript 側と 1 対 1 で、`ts-rs` が書き出します。**手で 2 か所に
 * 書きません**（§3）。dispatcher が網羅しているかどうかは、この型から作った
 * `Record` を TypeScript の型検査が見ます。
 */
export type AppAction = "addBoard" | "addCard" | "addColumn" | "addTag" | "saveEdit" | "undo" | "redo" | "cancelEdit" | "clearSearch" | "renameBoard" | "deleteBoard" | "manageTags" | "focusSearch" | "toggleBoardList" | "useLightTheme" | "useDarkTheme" | "useSystemTheme" | "about";
