// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ErrorKind } from "./ErrorKind";
import type { Field } from "./Field";

/**
 * コマンドの `Err`。
 */
export type AppError = { kind: ErrorKind, 
/**
 * ダイアログの見出し。
 */
title: string, 
/**
 * 使う人が手を打てる言葉に直したもの。
 */
detail: string, 
/**
 * 入力欄に返す場合だけ。`kind` が `Validation` のときに入る。
 */
field: Field | null, 
/**
 * 入力欄に返すとき、拒否された値。打ち直せるように返す。
 */
value: string | null, };
