// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DueCounts } from "./DueCounts";

export type BoardSummary = { id: number, name: string, createdAt: number, updatedAt: number, 
/**
 * ボードを開かずに読み取れる期限の件数。ボード一覧の各行に出す。
 */
due: DueCounts, };
