// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Board } from "./Board";

/**
 * 置き場所から読んだ盤面 1 つぶん。**webview が持つ形**（[ADR 0039]）。
 *
 * `Board` に、境界を越えない値（採番の続き）と版を添えたものです。採番の
 * 続きは画面が手元で番号を採るのに要り、版は保存の競合を見るのに要ります
 * （[ADR 0040]）。どちらも盤面の中身ではないので、`Board` の中には入れません。
 *
 * [ADR 0039]: ../../../docs/adr/0039-the-board-model-moves-to-typescript.md
 * [ADR 0040]: ../../../docs/adr/0040-the-shape-and-the-store-stay-in-rust.md
 */
export type BoardDocument = { board: Board, nextCardId: number, nextColumnId: number, nextTagId: number, nextChecklistItemId: number, 
/**
 * 保存のたびに 1 つ進む。手元のものと合わなければ、置き場所が断ります。
 */
rev: number, };
