// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type BoardSummary = { id: number, name: string, createdAt: number, updatedAt: number, };
