// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Card } from "./Card";
import type { Column } from "./Column";
import type { Recurrence } from "./Recurrence";
import type { Tag } from "./Tag";

export type Board = { id: number, name: string, createdAt: number, updatedAt: number, tags: Array<Tag>, archivedCards: Array<Card>, columns: Array<Column>, 
/**
 * 繰り返しの定義（#198）。**カードとは別に持ちます**（[ADR 0049]）。
 *
 * [ADR 0049]: ../../../docs/adr/0049-recurring-cards-are-defined-apart-from-the-board.md
 */
recurrences: Array<Recurrence>, };
