// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Card } from "./Card";
import type { Column } from "./Column";
import type { Tag } from "./Tag";

export type Board = { id: number, name: string, createdAt: number, updatedAt: number, tags: Array<Tag>, archivedCards: Array<Card>, columns: Array<Column>, };
