// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `capture:result` の積荷。
 */
export type CaptureResult = { "status": "saved", cardId: number, } | { "status": "failed", detail: string, };
