// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * クイックキャプチャが書き込む先。アプリ全体で 1 つ（`docs/DESIGN.md`）。
 */
export type CaptureTarget = { boardId: number, columnId: number, 
/**
 * 表示用に覚えておく名前。別のボードのカラムでも「どこに入るか」を出せるように。
 */
boardName: string, columnName: string, };
