// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CardEventKind } from "./CardEventKind";

/**
 * 積まれたカードの履歴 1 件。**次の保存で書き、書けたら捨てます。**
 *
 * 盤面を持つのは webview なので、履歴を積むのもそちら側です（[ADR 0039]）。
 * 置き場所は受け取ったものを追記するだけで、何が起きたかを見直しません。
 *
 * [ADR 0039]: ../../../docs/adr/0039-the-board-model-moves-to-typescript.md
 */
export type CardEvent = { cardId: number, kind: CardEventKind, fromColumnId: number | null, toColumnId: number | null, at: number, };
