// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DueStatus } from "./DueStatus";

/**
 * カード 1 枚の期限の状態。
 */
export type CardDueStatus = { cardId: number, status: DueStatus, };
