// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChecklistItem } from "./ChecklistItem";

export type Card = { id: number, columnId: number, title: string, description: string, position: number, createdAt: number, updatedAt: number, dueDate: string | null, tagIds: Array<number>, checklistItems: Array<ChecklistItem>, archivedAt: number | null, 
/**
 * このカードを出した繰り返しの定義（#198）。
 *
 * **参照であって、生成の真実ではありません。** 次を出すかどうかを決める
 * のは定義側の `last_generated_on` です（[ADR 0049]）。定義を消しても
 * この参照は残り、盤面のカードもそのまま残ります——指す先が消えたことは、
 * 画面が 🔁 を出さないことで表れます。
 *
 * [ADR 0049]: ../../../docs/adr/0049-recurring-cards-are-defined-apart-from-the-board.md
 */
recurrenceId: number | null, 
/**
 * このカードが受け持っている発生日（`"YYYY-MM-DD"`）。
 *
 * 片付ける相手を選ぶのに要ります——「次の発生日が来たら片付ける」の
 * 「次」は、この日から数えます（[ADR 0049]）。
 *
 * [ADR 0049]: ../../../docs/adr/0049-recurring-cards-are-defined-apart-from-the-board.md
 */
occurrenceDate: string | null, };
