// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChecklistItem } from "./ChecklistItem";

export type Card = { id: number, columnId: number, title: string, description: string, position: number, createdAt: number, updatedAt: number, dueDate: string | null, tagIds: Array<number>, checklistItems: Array<ChecklistItem>, archivedAt: number | null, };
