// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ChecklistItem = { id: number, cardId: number, text: string, checked: boolean, position: number, createdAt: number, updatedAt: number, };
