// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Card } from "./Card";

export type Column = { id: number, boardId: number, name: string, position: number, createdAt: number, updatedAt: number, 
/**
 * 終わったものの置き場か（[ADR 0038]）。
 *
 * **何本でも立てられます。** 「完了」と「キャンセル済み」は別の終わり方ですが、
 * もう手を動かさない点では同じなので、区別せず同じ扱いにします。ここに入って
 * いるカードは期限の件数に数えず、画面ではトーンダウンして描きます。
 *
 * [ADR 0038]: ../../../docs/adr/0038-a-column-that-means-done.md
 */
done: boolean, cards: Array<Card>, };
