// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Card } from "./Card";

export type Column = { id: number, boardId: number, name: string, position: number, createdAt: number, updatedAt: number, wipLimit: number | null, cards: Array<Card>, };
