// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 期限切れと本日期限のカードの枚数。
 *
 * 期限は表示するだけで通知しないので、見に行かなければ気づけない。ボードが
 * 増えると見に行く先も増えるので、開かなくても分かるようにこれを一覧に出す（#62）。
 */
export type DueCounts = { overdue: number, today: number, };
