// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 打った文字を期限としてどう読んだか（#134、[ADR 0031]）。
 *
 * **読み方を TypeScript にもう 1 つ持ちません**（`description_links` と同じ
 * 考え方）。往復するのは打った文字列と、読めた 1 日付だけです。読めない間は
 * `None` を返し、断りは保存のときに `Validation` で欄の脇へ出ます——打っている
 * 途中の文字はまだ間違いではありません。
 *
 * [ADR 0031]: ../../../docs/adr/0031-typing-a-due-date.md
 */
export type DueDatePreview = { 
/**
 * 保存する形（`"YYYY-MM-DD"`）。
 */
date: string, 
/**
 * 画面に出す形（`"2026-09-12（土）"`）。
 */
label: string, };
