// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DueStatus = { "kind": "overdue", "days": number } | { "kind": "today" } | { "kind": "soon", "days": number } | { "kind": "upcoming", "days": number } | { "kind": "none" };
