// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 失敗をどこに出すか。
 */
export type ErrorKind = "save" | "boardIo" | "export" | "shortcut" | "validation";
