// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 入力欄に返す失敗の行き先。
 */
export type Field = "cardTitle" | "dueDate" | "checklistItem" | "columnName" | "wipLimit" | "tagName" | "boardName";
