// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AppAction } from "./AppAction";
import type { Predefined } from "./Predefined";
import type { WindowAction } from "./WindowAction";

/**
 * メニュー 1 項目。**webview から届く形**（[ADR 0043]）。
 *
 * [ADR 0043]: ../../../docs/adr/0043-the-menu-is-described-by-the-webview.md
 */
export type Item = { "kind": "app", action: AppAction, 
/**
 * 文言。**使えない項目では理由まで入ります**——灰色の項目は押せず、
 * 理由を出す先が無いためです。
 */
label: string, 
/**
 * muda の書き方（`"CmdOrCtrl+N"`）。
 */
accelerator: string | null, 
/**
 * 押せるか。使えない環境の項目は灰色にして、消しはしません。
 */
enabled: boolean, } | { "kind": "window", action: WindowAction, label: string, accelerator: string | null, } | { "kind": "predefined", item: Predefined, } | { "kind": "separator" };
