// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 画面が押されたキーを渡す形。`KeyboardEvent` の modifiers と `code`。
 */
export type KeyPress = { ctrl: boolean, alt: boolean, shift: boolean, 
/**
 * macOS の Cmd、ほかの OS の Super。`KeyboardEvent.metaKey`。
 */
meta: boolean, 
/**
 * `KeyboardEvent.code`。**`key` ではありません**——`key` は修飾キーと配列で
 * 変わるので、同じ物理キーが別の名前で届きます。
 */
code: string, };
