// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 動いている OS。
 *
 * **webview に自分で当てさせません。** キーの割り当ては OS ごとに違い
 * （§7、[ADR 0009]）、`secondary` が Cmd か Ctrl かを取り違えると割り当てが
 * 丸ごと効かなくなります。`navigator.userAgent` は webview が書き換えられる
 * 文字列で、実際 Playwright の Safari 模擬は Linux 上で `Macintosh` を名乗り
 * ます。ここは Rust がコンパイル時に知っていることなので、そちらから渡します。
 *
 * [ADR 0009]: ../../../docs/adr/0009-per-platform-key-bindings.md
 */
export type Platform = "macos" | "windows" | "linux";
