// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * OS が持っている項目。ここに並ぶものを自分で書き直しません。
 *
 * 名前は `web/src/shell/menu.ts` の `Predefined` と 1 対 1 です。
 */
export type Predefined = "cut" | "copy" | "paste" | "selectAll" | "services" | "hide" | "hideOthers" | "showAll" | "about" | "minimize" | "zoom" | "closeWindow" | "fullscreen" | "quit";
