// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 前回のカードの片付け方（#198）。
 *
 * **未完了でも進行中のカラムにあっても同じように片付けます。** 選んだのは
 * この旗を立てた人で、置き場所がそこを読み替えません。
 */
export type PreviousPolicy = "keep" | "archive" | "delete";
