// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 割り当てのダイアログが開くときに読むもの。
 *
 * 型がここにあるのは、**殻を外した組み立てでも返す必要がある**ためです
 * （`crates/web`、[ADR 0035]）。中身を埋めるのは殻を持っている側
 * （`capture::status`）で、ブラウザでは「使えない理由」だけが入ります。
 *
 * [ADR 0035]: ../../../docs/adr/0035-a-browser-build-of-the-real-core.md
 */
export type QuickCaptureStatus = { 
/**
 * この環境でグローバルホットキーを使えないなら、その理由。使えるなら `null`。
 */
unavailable: string | null, 
/**
 * 保存されているのに登録できていない理由。効いているなら `null`。
 */
failure: string | null, };
