// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 割り当てのダイアログが開くときに読むもの。
 */
export type QuickCaptureStatus = { 
/**
 * この環境でグローバルホットキーを使えないなら、その理由。使えるなら `null`。
 */
unavailable: string | null, 
/**
 * 保存されているのに登録できていない理由。効いているなら `null`。
 */
failure: string | null, };
