// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 割り当てのダイアログが開くときに読むもの。
 *
 * 型がここにあるのは、**ブラウザ版も同じものを返す必要がある**ためです
 * （[ADR 0042]）。中身を埋めるのは殻を持っている側（`capture::status`）で、
 * ブラウザでは「使えない理由」だけが入ります。
 *
 * [ADR 0042]: ../../../docs/adr/0042-the-browser-build-is-the-same-typescript.md
 */
export type QuickCaptureStatus = { 
/**
 * この環境でグローバルホットキーを使えないなら、その理由。使えるなら `null`。
 */
unavailable: string | null, 
/**
 * 保存されているのに登録できていない理由。効いているなら `null`。
 */
failure: string | null, };
