// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PreviousPolicy } from "./PreviousPolicy";
import type { Schedule } from "./Schedule";

/**
 * 繰り返しの定義 1 つ（#198、[ADR 0049]）。
 *
 * **カードとは別のものです。** カード側が持つ `recurrence_id` は参照で、
 * 次を出すかどうかを決める真実はこちらの `last_generated_on` にあります。
 * カードから逆引きすると、手で消したカードが消した次の瞬間に生えてきます。
 *
 * 前半はテンプレート（出すカードの中身）、後半は周期と片付け方です。
 *
 * [ADR 0049]: ../../../docs/adr/0049-recurring-cards-are-defined-apart-from-the-board.md
 */
export type Recurrence = { id: number, boardId: number, title: string, description: string, 
/**
 * 入れ先のカラム。**消えていることがあります**——そのときは一番左に入ります。
 */
columnId: number, tagIds: Array<number>, 
/**
 * チェックリストのひな型。**項目に ID を持たせません**——テンプレートの
 * 項目は同一性を持たない文字列の並びで、ID を持つのは出来たカードのほうです。
 */
checklist: Array<string>, schedule: Schedule, 
/**
 * 発生日の何日前から出すか。`daily` / `weekday` は 0 に固定です
 * （毎日 `⚠` を 1 件増やさないため、期限も先読みも持ちません）。
 */
leadDays: number, previous: PreviousPolicy, enabled: boolean, 
/**
 * **生成の真実**。最後に出したカードの発生日（`"YYYY-MM-DD"`）。
 */
lastGeneratedOn: string | null, createdAt: number, updatedAt: number, };
