// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 繰り返しの周期（#198）。
 *
 * **`weekly{月〜金}` と `weekday` は分けてあります。** 見た目の並びは同じに
 * なりますが、祝日の扱いを持つのは後者だけです（いまはまだ曜日の意味しか
 * 持ちません）。片方に寄せると、祝日を足す日に受け皿が無くなります。
 *
 * 曜日は**月曜を 0** とした 0〜6 です。`web/src/model/dates.ts` の
 * `weekdayFromMonday` と同じ数え方で、`Date` の日曜 0 とは 1 つずれます。
 */
export type Schedule = { "kind": "daily" } | { "kind": "weekday" } | { "kind": "weekly", days: Array<number>, } | { "kind": "monthly", day: number, } | { "kind": "monthlyLast" };
