// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Item } from "./Item";

/**
 * メニューバーの 1 つぶん。
 */
export type Section = { name: string, items: Array<Item>, };
