// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Board } from "./Board";
import type { BoardSummary } from "./BoardSummary";

/**
 * 盤面を変えるコマンドが返すもの。
 */
export type Snapshot = { board: Board, 
/**
 * 期限の件数つきのボード一覧。サイドバーがこれを描く。
 */
boards: Array<BoardSummary>, canUndo: boolean, canRedo: boolean, 
/**
 * クイックキャプチャの入れ先が、このボードのどのカラムか。
 *
 * 設定が無ければ既定（先頭カラム）、別のボードを指していれば `None` です。
 * **印を出すのは画面ですが、どこが入れ先かを決めるのは Rust**——同じ既定を
 * TypeScript にもう 1 つ持たせません。
 */
captureColumn: number | null, 
/**
 * ウィンドウのタイトル。webview がそのまま `set_window_title` に渡します。
 *
 * 組み立てを TypeScript に持たせません。ボード名の扱い（空白だけの名前は
 * アプリ名だけにする）は表示の判断なので、盤面の判断と同じところに置きます。
 */
windowTitle: string, };
