// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Board } from "./Board";
import type { BoardSummary } from "./BoardSummary";
import type { CardDueStatus } from "./CardDueStatus";

/**
 * 盤面を変えるコマンドが返すもの。
 */
export type Snapshot = { board: Board, 
/**
 * 期限の件数つきのボード一覧。サイドバーがこれを描く。
 */
boards: Array<BoardSummary>, canUndo: boolean, canRedo: boolean, 
/**
 * 期限を持つカードの、いま時点での状態。
 *
 * `due_status` は `model.rs` の純粋関数で、判定は Rust に残します（§5）。
 * カードそのものには載せられません——`Card` はデータベースから来るもので、
 * 「今日が何日か」を知らないからです。
 *
 * **日付をまたぐと古くなります。** 開きっぱなしで日が変わると、次に何か
 * コマンドを呼ぶまで昨日の判定が出たままになります。`today` を一緒に返す
 * のはそのためで、webview は手元の日付とずれたら読み直せます。
 */
dueStatuses: Array<CardDueStatus>, 
/**
 * `due_statuses` を出したときの日付。
 */
today: string, 
/**
 * クイックキャプチャの入れ先が、このボードのどのカラムか。
 *
 * 設定が無ければ既定（先頭カラム）、別のボードを指していれば `None` です。
 * **印を出すのは画面ですが、どこが入れ先かを決めるのは Rust**——同じ既定を
 * TypeScript にもう 1 つ持たせません。
 */
captureColumn: number | null, 
/**
 * ウィンドウのタイトル。webview がそのまま `set_window_title` に渡します。
 *
 * 組み立てを TypeScript に持たせません。ボード名の扱い（空白だけの名前は
 * アプリ名だけにする）は表示の判断なので、盤面の判断と同じところに置きます。
 */
windowTitle: string, };
