// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Board } from "./Board";
import type { BoardSummary } from "./BoardSummary";

/**
 * 盤面を変えるコマンドが返すもの。
 */
export type Snapshot = { board: Board, 
/**
 * 期限の件数つきのボード一覧。サイドバーがこれを描く。
 */
boards: Array<BoardSummary>, canUndo: boolean, canRedo: boolean, };
