// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CaptureTarget } from "./CaptureTarget";
import type { FilterState } from "./FilterState";
import type { Platform } from "./Platform";
import type { ThemePreference } from "./ThemePreference";
import type { WindowBoundsState } from "./WindowBoundsState";

/**
 * 起動のときと、ウィンドウを開き直すときに読むもの。
 *
 * メモリ上の値を抱えて使い回しません。ウィンドウを閉じている間もクイック
 * キャプチャはカードを足せるので、閉じたときの値で開き直すと古い盤面が出ます
 * （`docs/DESIGN.md`）。
 */
export type StartupState = { 
/**
 * 最初に開くボード。**盤面そのものは渡しません**——webview が
 * `load_documents` で全部読みます（[ADR 0039]）。
 *
 * [ADR 0039]: ../../../docs/adr/0039-the-board-model-moves-to-typescript.md
 */
openBoardId: number, 
/**
 * 動いている OS。キーの割り当てを決めるのに使います。
 */
platform: Platform, filter: FilterState, windowBounds: WindowBoundsState | null, theme: ThemePreference, sidebarCollapsed: boolean, 
/**
 * 日付が変わる時刻（0〜23、既定は 4）。基準日を作るのに使います（[ADR 0048]）。
 *
 * **基準日は 1 つだけ**です。カードの `⚠` もボード一覧の件数も、画面が
 * この時刻から作った 1 つの基準日から出ます。
 *
 * [ADR 0048]: ../../../docs/adr/0048-the-day-turns-at-four-in-the-morning.md
 */
dayBoundaryHour: number, captureTarget: CaptureTarget | null, 
/**
 * 保存されている割り当て。登録できるかどうかは別の話（`docs/DESIGN.md`「クイックキャプチャ」）。
 */
quickCaptureShortcut: string | null, 
/**
 * 動いているアプリの版（#147）。
 *
 * **出どころは `CARGO_PKG_VERSION` の 1 つだけ**です。webview 側の
 * `package.json` の版はアプリの版ではないので、そちらは見ません。
 */
version: string, 
/**
 * いま開いているデータベースのフルパス（#147）。
 *
 * `EKANBAN_DATABASE` で差し替えていればそれが入ります。「場所を開く」で
 * 開けるだけでは、どのファイルを見ているのかを文字で読めませんでした。
 */
databasePath: string, };
