// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CaptureTarget } from "./CaptureTarget";
import type { FilterState } from "./FilterState";
import type { Snapshot } from "./Snapshot";
import type { ThemePreference } from "./ThemePreference";
import type { WindowBoundsState } from "./WindowBoundsState";

/**
 * 起動のときと、ウィンドウを開き直すときに読むもの。
 *
 * メモリ上の値を抱えて使い回しません。ウィンドウを閉じている間もクイック
 * キャプチャはカードを足せるので、閉じたときの値で開き直すと古い盤面が出ます
 * （`docs/DESIGN.md`）。
 */
export type StartupState = { 
/**
 * 盤面そのもの。`board:changed` で届くのと同じ形なので、webview は
 * 起動でもイベントでも同じ 1 本の経路で差し替えられます（§4）。
 */
snapshot: Snapshot, filter: FilterState, windowBounds: WindowBoundsState | null, theme: ThemePreference, sidebarCollapsed: boolean, captureTarget: CaptureTarget | null, 
/**
 * 保存されている割り当て。登録できるかどうかは別の話（§9）。
 */
quickCaptureShortcut: string | null, };
