// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Tag = { id: number, boardId: number, name: string, color: string, createdAt: number, updatedAt: number, };
