// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * テーマの設定。`app_state` に文字列で入っている。
 */
export type ThemePreference = "system" | "light" | "dark";
