// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 説明の中の URL の位置（[ADR 0002]）。
 *
 * 位置は **UTF-16 の符号単位**で数えます。JavaScript の文字列がその単位なので、
 * Rust の byte 位置をそのまま渡すと、日本語の説明で 1 文字ぶんずつずれます。
 *
 * [ADR 0002]: ../../../docs/adr/0002-links-inside-the-description-field.md
 */
export type UrlSpan = { start: number, end: number, url: string, };
