// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AppAction } from "./AppAction";

/**
 * ページが描くメニューの 1 項目。
 */
export type WebItem = { "kind": "action", action: AppAction, label: string, 
/**
 * muda の書き方（`"CmdOrCtrl+N"`）のまま渡します。**押されたキーと
 * 突き合わせるのも、画面に出す形にするのもページの仕事**です——
 * ブラウザにはアクセラレータを引き受けるメニューバーが無いので、
 * `web/src/shell/accelerator.ts` が受けます。
 */
accelerator: string | null, enabled: boolean, } | { "kind": "separator" };
