// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WebItem } from "./WebItem";

/**
 * ページが描くメニューバーの 1 つぶん（[ADR 0035]）。
 *
 * [ADR 0035]: ../../../docs/adr/0035-a-browser-build-of-the-real-core.md
 */
export type WebSection = { name: string, items: Array<WebItem>, };
