// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Rust が行うウィンドウの操作。
 *
 * macOS では同じことを [`Predefined`] が持っているので、こちらに出てくるのは
 * macOS 以外だけです（`Alt+F4` や `Ctrl+Q` を OS 側の項目が持っていない）。
 */
export type WindowAction = "closeWindow" | "toggleFullscreen" | "quit";
